name: deploy_docs

on:
  push:
    branches: [ main ]

jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true

      - name: Cache poetry venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-docs-python3.7-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install -E docs --without dev

      - name: Build site
        run: poetry run mkdocs build

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: ./site
